CREATE TABLE canskate_ribbon_log (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  skater_id INTEGER REFERENCES skaters(id) NOT NULL,
  ribbon_id TEXT REFERENCES canskate_ribbons(id) NOT NULL,
  date_completed DATE DEFAULT now() NOT NULL,
  UNIQUE (skater_id, ribbon_id)
);