# /skater routes

GET http://localhost:8000/api/skater/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hcmN1c2VzMTAxIiwiaWF0IjoxNjEwMDM5NjE0fQ.v-98WyQJsvzfWAjzHNOa1HJSt12q6AHp69ZjkYKzcRs
###

POST http://localhost:8000/api/session HTTP/1.1
Content-Type: application/json

{
  "duration":55,
  "day":"Wednesday",
  "start_time":"12:00:00",
  "club_id":1
}

###

POST http://localhost:8000/api/skater HTTP/1.1
Content-Type: application/json

{
  "fullname": "Camille Ruest",
  "gender": "Female",
  "birthdate": "1993-11-23"
}

###
POST http://localhost:8000/api/skater-club HTTP/1.1
Content-Type: application/json

{
  "skater_id": 101,
  "club_id": 4
}

###
DELETE http://localhost:8000/api/skater-club/ HTTP/1.1
Content-Type: application/json

{
  "skater_id": 3,
  "club_id": 4
}

###

POST http://localhost:8000/api/skater-session HTTP/1.1
Content-Type: application/json

{
  "skater_id": 101,
  "session_id": 4
}

###

DELETE http://localhost:8000/api/skater-session HTTP/1.1
Content-Type: application/json

{
  "skater_id":101,
  "session_id":4
}

###

POST https://hidden-garden-48711.herokuapp.com/api/skater-group HTTP/1.1
Content-Type: application/json

{
  "skater_id": 101,
  "group_id": 5

}

###

POST http://localhost:8000/api/skater-group HTTP/1.1
Content-Type: application/json

{
  "skater_id": 101,
  "group_id": 5
}

###
PATCH http://localhost:8000/api/skater-group HTTP/1.1
Content-Type: application/json

{
  "skater_id":101,
  "group_id": 5,
  "new_group_id": 3
}

###

GET http://localhost:8000/api/skater/30 HTTP/1.1


###
PATCH http://localhost:8000/skater/202 HTTP/1.1
Content-Type: application/json

{
  "fullname": "Marcus Nathan James Connolly"
}

###

PATCH http://localhost:8000/api/club/4 HTTP/1.1
Content-Type: application/json

{
  "name": "Marcus's Super Cool Club"
}

###
DELETE http://localhost:8000/skater/202 HTTP/1.1

# /groups

# /sessions

###
# /api/element

GET http://localhost:8000/api/element HTTP/1.1

###

GET http://localhost:8000/api/log HTTP/1.1

###
GET http://localhost:8000/api/club/4 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hcmN1c2VzMTAxIiwiaWF0IjoxNjEwMDM5NjE0fQ.v-98WyQJsvzfWAjzHNOa1HJSt12q6AHp69ZjkYKzcRs

###

PATCH http://localhost:8000/api/club/15 HTTP/1.1
Content-Type: application/json

{
  "name":"bob's club"
}

###

GET https://hidden-garden-48711.herokuapp.com/api/skater HTTP/1.1

###
POST https://hidden-garden-48711.herokuapp.com/api/skater HTTP/1.1
Content-Type: application/json

{
  "fullname": "Camille Ruest",
  "gender": "Female",
  "birthdate": "1993-11-23"
}

###

POST http://localhost:8000/api/club HTTP/1.1
Content-Type: application/json

{"name": "Brand New Club!"}

###
GET http://localhost:8000/login