CREATE TYPE sex AS ENUM(
  'Male','Female', 'Other'
);

CREATE TABLE skaters (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  fullname TEXT NOT NULL,
  gender sex NOT NULL,
  birthdate DATE NOT NULL
);