CREATE TABLE canskate_element_log (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  skater_id INTEGER REFERENCES skaters(id) NOT NULL,
  element_id TEXT REFERENCES canskate_elements(id) NOT NULL,
  date_completed DATE DEFAULT now() NOT NULL
);

ALTER TABLE canskate_element_log ADD CONSTRAINT unique_skater_element UNIQUE (skater_id, element_id);