CREATE TABLE skater_element_log (
   id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  skater_id INTEGER REFERENCES skaters(id) NOT NULL,
  element_id TEXT REFERENCES elements(id) NOT NULL,
  date_completed TIMESTAMPTZ DEFAULT now() NOT NULL,
  UNIQUE (skater_id, element_id)
)