CREATE TABLE skater_checkmark_log (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  skater_id INTEGER REFERENCES skaters(id) NOT NULL,
  checkmark_id TEXT REFERENCES checkmarks(id) NOT NULL,
  date_completed TIMESTAMPTZ DEFAULT now() NOT NULL,
  UNIQUE (skater_id, checkmark_id)
);