CREATE TABLE skater_ribbon_log (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  skater_id INTEGER REFERENCES skaters(id) NOT NULL,
  ribbon_id TEXT REFERENCES ribbons(id) NOT NULL,
  date_completed TIMESTAMPTZ DEFAULT now() NOT NULL,
  date_distributed TIMESTAMPTZ,
  UNIQUE (skater_id, ribbon_id)
)