CREATE TABLE skater_session (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  skater_id INTEGER REFERENCES skaters(id) NOT NULL,
  session_id INTEGER REFERENCES sessions(id) NOT NULL,
  UNIQUE (skater_id, session_id)
);