CREATE TABLE canskate_badge_log(
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  skater_id INTEGER REFERENCES skaters(id) NOT NULL,
  badge_id INTEGER REFERENCES canskate_badges(id) NOT NULL,
  date_completed DATE DEFAULT now() NOT NULL
)