CREATE TABLE canskate_skater_session (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  skater_id INTEGER REFERENCES skaters(id) ON DELETE CASCADE NOT NULL,
  session_id INTEGER REFERENCES canskate_sessions(id) ON DELETE CASCADE NOT NULL,
  UNIQUE (skater_id, session_id)
);