CREATE TABLE skater_group (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  skater_id INTEGER REFERENCES skaters(id) NOT NULL,
  group_id INTEGER REFERENCES groups(id) NOT NULL,
  UNIQUE (skater_id, group_id)
)